### ISSUE TITLE
HOME: Ticker title and banner image flickers when clicking home button. Occurs only using chrome.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/The-Cancer-Centre#15]
http://screencast.com/t/XOjXzdmO

**Comment by euveng** [comment]
This is due to the fact that the carousel script is loaded in the footer. The browser will load the dom which includes content from all slides. Only after the dom is loaded, the slider will be initialised, which activates the slides. This can be resolved by loading the carousel script in the header, but this should be avoided to preserve fast loading speed. Therefore will not fix.

**Comment by iteano** [comment]
Just want to clarify, is this a chrome limitation? why this isn't happening on the other browser?

**Comment by euveng** [comment]
Not sure about the answer to this question, will have to investigate.
